//
//  MockData.swift
//  CurrencyConverterApp
//
//  Created by estelle on 7/13/25.
//

/*
 let mockData: [ExchangeRateData] = [
 ExchangeRateData(currencyCode:"USD", country: "미국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"AED", country: "아랍에미리트", rate: 3.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"AFN", country: "아프가니스탄", rate: 70.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ALL", country: "알바니아", rate: 81.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"AMD", country: "아르메니아", rate: 331.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ANG", country: "네덜란드령 안틸레스", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"AOA", country: "앙골라", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ARS", country: "아르헨티나", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"AUD", country: "오스트레일리아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"AWG", country: "아루바", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"AZN", country: "아제르바이잔", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BAM", country: "보스니아 헤르체고비나", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BBD", country: "바베이도스", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BDT", country: "방글라데시", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BGN", country: "불가리아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BHD", country: "바레인", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BIF", country: "부룬디", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BMD", country: "버뮤다", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BND", country: "브루나이", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BOB", country: "볼리비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BRL", country: "브라질", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BSD", country: "바하마", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BTN", country: "부탄", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BWP", country: "보츠와나", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BYN", country: "벨라루스", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"BZD", country: "벨리즈", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CAD", country: "캐나다", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CDF", country: "콩고민주공화국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CHF", country: "스위스", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CLP", country: "칠레", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CNY", country: "중국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"COP", country: "콜롬비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CRC", country: "코스타리카", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CUP", country: "쿠바", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CVE", country: "카보베르데", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"CZK", country: "체코", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"DJF", country: "지부티", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"DKK", country: "덴마크", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"DOP", country: "도미니카공화국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"DZD", country: "알제리", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"EGP", country: "이집트", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ERN", country: "에리트레아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ETB", country: "에티오피아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"EUR", country: "유럽연합", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"FJD", country: "피지", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"FKP", country: "포클랜드제도", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"FOK", country: "페로제도", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GBP", country: "영국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GEL", country: "조지아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GGP", country: "건지", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GHS", country: "가나", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GIP", country: "지브롤터", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GMD", country: "감비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GNF", country: "기니", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GTQ", country: "과테말라", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"GYD", country: "가이아나", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"HKD", country: "홍콩", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"HNL", country: "온두라스", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"HRK", country: "크로아티아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"HTG", country: "아이티", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"HUF", country: "헝가리", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"IDR", country: "인도네시아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ILS", country: "이스라엘", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"IMP", country: "맨섬", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"INR", country: "인도", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"IQD", country: "이라크", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"IRR", country: "이란", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ISK", country: "아이슬란드", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"JEP", country: "저지섬", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"JMD", country: "자메이카", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"JOD", country: "요르단", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"JPY", country: "일본", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KES", country: "케냐", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KGS", country: "키르기스스탄", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KHR", country: "캄보디아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KID", country: "키리바시", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KMF", country: "코모로", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KRW", country: "대한민국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KWD", country: "쿠웨이트", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KYD", country: "케이맨 제도", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"KZT", country: "카자흐스탄", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"LAK", country: "라오스", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"LBP", country: "레바논", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"LKR", country: "스리랑카", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"LRD", country: "라이베리아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"LSL", country: "레소토", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"LYD", country: "리비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MAD", country: "모로코", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MDL", country: "몰도바", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MGA", country: "마다가스카르", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MKD", country: "북마케도니아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MMK", country: "미얀마", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MNT", country: "몽골", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MOP", country: "마카오", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MRU", country: "모리타니", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MUR", country: "모리셔스", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MVR", country: "몰디브", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MWK", country: "말라위", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MXN", country: "멕시코", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MYR", country: "말레이시아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"MZN", country: "모잠비크", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"NAD", country: "나미비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"NGN", country: "나이지리아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"NIO", country: "니카라과", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"NOK", country: "노르웨이", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"NPR", country: "네팔", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"NZD", country: "뉴질랜드", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"OMR", country: "오만", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"PAB", country: "파나마", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"PEN", country: "페루", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"PGK", country: "파푸아뉴기니", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"PHP", country: "필리핀", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"PKR", country: "파키스탄", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"PLN", country: "폴란드", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"PYG", country: "파라과이", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"QAR", country: "카타르", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"RON", country: "루마니아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"RSD", country: "세르비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"RUB", country: "러시아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"RWF", country: "르완다", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SAR", country: "사우디아라비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SBD", country: "솔로몬 제도", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SCR", country: "세이셸", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SDG", country: "수단", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SEK", country: "스웨덴", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SGD", country: "싱가포르", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SHP", country: "세인트헬레나", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SLE", country: "시에라리온", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SLL", country: "시에라리온", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SOS", country: "소말리아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SRD", country: "수리남", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SSP", country: "남수단", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"STN", country: "상투메 프린시페", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SYP", country: "시리아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"SZL", country: "에스와티니", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"THB", country: "태국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TJS", country: "타지키스탄", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TMT", country: "투르크메니스탄", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TND", country: "튀니지", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TOP", country: "통가", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TRY", country: "튀르키예", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TTD", country: "트리니다드 토바고", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TVD", country: "투발루", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TWD", country: "대만", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"TZS", country: "탄자니아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"UAH", country: "우크라이나", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"UGX", country: "우간다", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"UYU", country: "우루과이", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"UZS", country: "우즈베키스탄", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"VES", country: "베네수엘라", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"VND", country: "베트남", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"VUV", country: "바누아투", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"WST", country: "사모아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"XAF", country: "중앙아프리카 CFA 프랑", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"XCD", country: "동카리브 제도", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"XCG", country: "가상통화 (Crypto Generic)", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"XDR", country: "IMF 특별인출권", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"XOF", country: "서아프리카 CFA 프랑", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"XPF", country: "프랑스령 폴리네시아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"YER", country: "예멘", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ZAR", country: "남아프리카 공화국", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ZMW", country: "잠비아", rate: 1.0, changeStatus: .down),
 ExchangeRateData(currencyCode:"ZWL", country: "짐바브웨", rate: 1.0, changeStatus: .down)
 ]
 
 */


let mockData = [
  "USD": 1,
  "AED": 3.2725,
  "AFN": 59.297423,
  "ALL": 93.539999,
  "AMD": 374.116071,
  "ANG": 1.69,
  "AOA": 929.975683,
  "ARS": 1161.58,
  "AUD": 1.620469,
  "AWG": 1.69,
  "AZN": 1.800669,
  "BAM": 1.773298,
  "BBD": 2,
  "BDT": 124.682395,
  "BGN": 1.473323,
  "BHD": 0.376,
  "BIF": 2961.716264,
  "BMD": 1,
  "BND": 1.380553,
  "BOB": 6.923461,
  "BRL": 5.454239,
  "BSD": 1,
  "BTN": 87.871274,
  "BWP": 14.44242,
  "BYN": 3.057007,
  "BZD": 2,
  "CAD": 1.37888,
  "CDF": 2887.321107,
  "CHF": 0.696621,
  "CLP": 951.099277,
  "CNY": 7.574595,
  "COP": 4025.610084,
  "CRC": 505.452488,
  "CUP": 24,
  "CVE": 93.43654,
  "CZK": 21.097404,
  "DJF": 177.521,
  "DKK": 6.482538,
  "DOP": 60.225215,
  "DZD": 125.767121,
  "EGP": 49.711805,
  "ERN": 15.4,
  "ETB": 166.374949,
  "EUR": 0.655545,
  "FJD": 2.247068,
  "FKP": 0.440441,
  "FOK": 6.382538,
  "GBP": 0.740444,
  "GEL": 2.615752,
  "GGP": 0.840441,
  "GHS": 13.692189,
  "GIP": 0.740441,
  "GMD": 72.768149,
  "GNF": 8285.104232,
  "GTQ": 7.586352,
  "GYD": 204.191086,
  "HKD": 7.750051,
  "HNL": 26.462408,
  "HRK": 6.546095,
  "HTG": 170.966873,
  "HUF": 341.807431,
  "IDR": 16235.840289,
  "ILS": 3.629642,
  "IMP": 0.540441,
  "INR": 85.571396,
  "IQD": 1399.762078,
  "IRR": 42245.119165,
  "ISK": 122.741341,
  "JEP": 0.740441,
  "JMD": 159.883697,
  "JOD": 0.709,
  "JPY": 147.167812,
  "KES": 129.584036,
  "KGS": 87.404019,
  "KHR": 4013.363819,
  "KID": 1.320468,
  "KMF": 423.899969,
  "KRW": 1376.462043,
  "KWD": 0.605596,
  "KYD": 0.333333,
  "KZT": 519.523709,
  "LAK": 21644.811132,
  "LBP": 89500,
  "LKR": 303.650944,
  "LRD": 200.544054,
  "LSL": 17.502852,
  "LYD": 5.50634,
  "MAD": 9.5076,
  "MDL": 16.32268,
  "MGA": 4413.96223,
  "MKD": 52.767973,
  "MMK": 2102.719682,
  "MNT": 3619.394541,
  "MOP": 8.085552,
  "MRU": 39.554001,
  "MUR": 45.563336,
  "MVR": 15.350074,
  "MWK": 1744.235291,
  "MXN": 18.659546,
  "MYR": 4.251795,
  "MZN": 63.314027,
  "NAD": 17.902852,
  "NGN": 1529.579003,
  "NIO": 36.312533,
  "NOK": 10.328064,
  "NPR": 137.594038,
  "NZD": 1.564495,
  "OMR": 0.584497,
  "PAB": 1,
  "PEN": 3.550134,
  "PGK": 4.387423,
  "PHP": 56.508761,
  "PKR": 284.571587,
  "PLN": 3.642515,
  "PYG": 7857.528154,
  "QAR": 3.64,
  "RON": 4.336532,
  "RSD": 100.545556,
  "RUB": 78.512988,
  "RWF": 1447.626981,
  "SAR": 3.75,
  "SBD": 8.359325,
  "SCR": 14.399505,
  "SDG": 503.974176,
  "SEK": 9.351981,
  "SGD": 1.280553,
  "SHP": 0.340441,
  "SLE": 22.453134,
  "SLL": 22455.133894,
  "SOS": 571.359411,
  "SRD": 37.391305,
  "SSP": 4682.582894,
  "STN": 20.960824,
  "SYP": 12896.659549,
  "SZL": 17.502852,
  "THB": 32.42141,
  "TJS": 10.314374,
  "TMT": 3.439805,
  "TND": 2.302929,
  "TOP": 2.38074,
  "TRY": 40.502703,
  "TTD": 6.765742,
  "TVD": 1.520468,
  "TWD": 29.140192,
  "TZS": 2604.909384,
  "UAH": 41.396998,
  "UGX": 3563.376257,
  "UYU": 40.608468,
  "UZS": 12638.872207,
  "VES": 115.3279,
  "VND": 26038.663047,
  "VUV": 119.247002,
  "WST": 2.733067,
  "XAF": 561.399959,
  "XCD": 2.7,
  "XCG": 1.79,
  "XDR": 0.730093,
  "XOF": 561.399959,
  "XPF": 102.093755,
  "YER": 242.187676,
  "ZAR": 17.830699,
  "ZMW": 23.387002,
  "ZWL": 28.8394
]

